# use the default Python on Travis CI
sudo: required
dist: trusty
language: python

# install tools for checking markdown
install:
  - pip install proselint
  - gem install mdl

# cache to speed installation
cache:
  directories:
    - $HOME/.pip-cache/

# run checks on Markdown writing through mdl and proselint
script:
  - mdl README.md
  - proselint README.md
  - mdl pycon_2018_collaborative_software.md
  - mdl pyohio_2018_teaching_programming.md
  - mdl pygotham_2018_teaching_programming.md
